name: CI Linux

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    steps:
    - name: setup-graalvm
      uses: rtc11/setup-graalvm@master
      with:
        args: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-linux-amd64-20.0.0.tar.gz

    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        java -version
