name: CI Linux

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Graal VM
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '20.0.0.java8'
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Verify java version
      run: |
        java -version
    - name: Cache Maven local repository
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Maven build
      run: |
        mvn clean install
    - name: Check artifacts
      run: |
        ls -al target/
