name: CI Windows

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: setup-graalvm
      uses: rtc11/setup-graalvm@master
      with:
        args: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-windows-amd64-20.0.0.zip

    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        java -version
