name: CI Windows

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '19.3.0.java8' // GraalVM version, no pattern syntax available atm.
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        java -version
